{% set data = load_setup_py_data() %}

package:
  name: craft-text-detector
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - numpy>=1.11.1
    - scipy
    - opencv
    - pytorch>=0.4.1
    - torchvision>=0.2.1

  run:
    - python
    - numpy>=1.11.1
    - scipy
    - opencv
    - gdown>=3.10.1
    - pytorch>=0.4.1
    - torchvision>=0.2.1

test:
  imports:
    - craft_text_detector

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
summary: {{ data['description'] }}
